create table category
(
    id          bigint generated by default as identity,
    description varchar(255),
    name        varchar(255),
    primary key (id)
);
create table order_item
(
    id         bigint generated by default as identity,
    price      float(53),
    quantity   integer,
    order_id   bigint,
    product_id bigint,
    primary key (id)
);
create table orders
(
    total_amount float(53),
    id           bigint generated by default as identity,
    order_date   timestamp(6),
    user_id      bigint,
    primary key (id)
) ;
create table product
(
    price       float(53),
    category_id bigint,
    id          bigint generated by default as identity,
    description varchar(255),
    name        varchar(255),
    primary key (id)
) ;
create table users
(
    id       bigint generated by default as identity,
    mail     varchar(255),
    password varchar(255),
    username varchar(255),
    primary key (id)
) ;
alter table if exists order_item
    add constraint FKt4dc2r9nbvbujrljv3e23iibt foreign key (order_id) references orders;
alter table if exists order_item
    add constraint FK551losx9j75ss5d6bfsqvijna foreign key (product_id) references product;
alter table if exists orders
    add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users;
alter table if exists product
    add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category;